### PR TITLE
Add configurable tag threshold and classifier

### PR DESCRIPTION
**Pull request by nidi3**
Threshold: minimum occurrences of a tag in order to be included in the tag cloud
Classifier: How to map the number of tag occurrences into [1..5], can be log or linear

### CODE REVIEW

**Comment by nhoizey** [comment]
Looks amazing!

**Comment by nhoizey** [comment]
@pattex any chance to add these really important features to the plugin? Thanks

**Comment by nhoizey** [comment]
@nidi3 it would be nice to have 2 different PRs, maybe, to help @pattex decide

**Comment by nidi3** [comment]
Oh, it's a long time ago @pattex would it really help?

**Comment by nhoizey** [comment]
@nidi3 I would still use it, I hope @pattex will merge it soon…

**Comment by nidi3** [comment]
Ok, after 2.5 years, here you go: #66 #67

**Comment by nhoizey** [comment]
@nidi3 I guess this PR can be closed, if everything is in #66 and #67

**Comment by nidi3** [comment]
I agree.

**Pull request closed without merging**
