### PR TITLE
Support site.config["baseurl"]

### PR DESCRIPTION
**Pull request by henry0312**

### CODE REVIEW

**Comment by adamchainz** [comment]
+1

**Comment by pattex** [comment]
Would you please take a look if this does the trick now?
In your `_config.yml` it is `base_url`.

**Comment by adamchainz** [comment]
Did: `gem specific_install git@github.com:pattex/jekyll-tagging.git` and it allowed me to get rid of my patch with `jekyll serve`. Also tested removing `baseurl` from my config and it still worked. Thanks! Looking forward to rubygems release.

**Comment by pattex** [comment]
Great, thank you.

**Pull request merged**
