### PR TITLE
Call to_s on the tags before processing

### PR DESCRIPTION
**Pull request by queirozfcom**
Because some tags may be things like number or reserved words,  and then you'll get `undefined_method remove_diacritics` for Float, and so on. Calling `to_s` before fixed it for me.

### CODE REVIEW

**Comment by amcewen** [comment]
I hit this problem too, and @queirozfcom's fix seems to do the trick (thanks @queirozfcom!)

**Comment by queirozfcom** [comment]
Well until it's merged or otherwise fixed, I'm using `gem 'jekyll-tagging', :git => 'https://github.com/queirozfcom/jekyll-tagging.git'` in my `Gemfile` @amcewen

**Comment by amcewen** [comment]
@queirozfcom Ah, hadn't realised you could do that with gem - I'm patching it afterwards at the minute.  Thanks!

**Comment by nhoizey** [comment]
Had the same issue, any way to accelerate Pull Request merging?

**Comment by pattex** [comment]
Hey, I only merged ed09d3d7b6590d242fe8b57948881567cb000f0e

Thanks a lot and greetings
pattex - the worst open source maintainer of the galaxy

**Comment by nhoizey** [comment]
Thanks @pattex !

**Pull request closed without merging**
